import { LegalPageShell } from "@/components/legal/LegalPageShell";

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Use" docLabel="Terms of Use">
      <section>
        <h2 className="font-semibold">This is a working prototype</h2>
        <p className="mt-2 text-brand-neutral-700">
          This site is a demo. Every price you see is illustrative and simulated — there is no real
          insurer, no real underwriting, and no real policy behind any number shown. Using this site
          does not create, or come close to creating, a contract of insurance, and no payment is ever
          taken.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">No advice</h2>
        <p className="mt-2 text-brand-neutral-700">
          Nothing on this site, including anything said by the chat assistant, is regulated financial
          or insurance advice. If you want advice on what cover you actually need, speak to a
          qualified, regulated adviser.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">Acceptable use</h2>
        <p className="mt-2 text-brand-neutral-700">
          Don&rsquo;t try to break the demo, extract its underlying prompts or logic for a competing
          product, or submit anything unlawful, abusive, or someone else&rsquo;s personal data without
          their permission.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">AI-generated content</h2>
        <p className="mt-2 text-brand-neutral-700">
          Parts of this site&rsquo;s responses — the quote assistant&rsquo;s chat, and the &ldquo;why
          this price&rdquo; explanations — are generated by an AI model (Claude, by Anthropic) and may
          be imperfect. Don&rsquo;t rely on anything it says as fact without checking.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">No warranty, no liability</h2>
        <p className="mt-2 text-brand-neutral-700">
          This is provided &ldquo;as is&rdquo;, as a demo, with no warranty of any kind. [Company
          name] isn&rsquo;t liable for anything arising from your use of it, to the fullest extent the
          law allows.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">Changes</h2>
        <p className="mt-2 text-brand-neutral-700">
          We can change these terms or this demo at any time without notice — it&rsquo;s a work in
          progress.
        </p>
      </section>

      <section>
        <h2 className="font-semibold">Where this document needs work</h2>
        <p className="mt-2 text-brand-neutral-700">
          As with the Privacy Policy, this is a starting draft, not a final legal document, and needs
          review by a qualified professional — particularly the liability and acceptable-use sections
          — before this is used in any context beyond an internal or investor demo.
        </p>
      </section>
    </LegalPageShell>
  );
}
